apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-3
  labels:
    app: mongo-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-3
  template:
    metadata:
      labels:
        app: mongo-3
    spec:
      containers:
        - name: mongo-3
          image: mongo:latest
          env:
            - name: MONGO_INITDB_DATABASE
              value: inno-payment-db
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          envFrom:
            - secretRef:
                name: app-config-secret
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
          command:
            - bash
            - -c
            - |
              if [ ! -f /data/db/mongo.key ]; then
              echo ${MONGO_KEY} > /data/db/mongo.key &&
              chmod 400 /data/db/mongo.key;
              fi &&
              
              chmod -R 755 /data/db/.mongodb/mongosh/ || true
              
              exec docker-entrypoint.sh mongod --replSet rs0 --bind_ip_all --keyFile /data/db/mongo.key --auth
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
                - admin
                - -u
                - admin
                - -p
                - admin
                - --authenticationDatabase
                - admin
                - --quiet
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
                - admin
                - -u
                - admin
                - -p
                - admin
                - --authenticationDatabase
                - admin
                - --quiet
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: wait-for-consumer
        resources:
          requests:
            storage: 1Gi