apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-postgres
  template:
    metadata:
      labels:
        app: user-service-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: inno-users-db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U postgres -d inno-users-db"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U postgres -d inno-users-db"
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: user-service-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-postgres
spec:
  selector:
    app: user-service-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi