apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-service-postgres
  labels:
    app: auth-service-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-postgres
  template:
    metadata:
      labels:
        app: auth-service-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: inno-auth-db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 500m
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d inno-auth-db
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d inno-auth-db
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 15
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: wait-for-consumer
        resources:
          requests:
            storage: 1Gi